######################################################################
# Automatically generated by qmake (2.00a) Ter Set 27 19:38:08 2005
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

QT += network
CONFIG += qt release

# Input
HEADERS += common.h configuracao.h editor_paleta.h visualizacao.h paintbrush.h
SOURCES += configuracao.cpp editor_paleta.cpp main.cpp visualizacao.cpp paintbrush.cpp
