######################################################################
# Automatically generated by qmake (2.00a) Dom Mar 19 18:24:29 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .
# CONFIG += debug warn_on
CONFIG += release warn_on

# Input
HEADERS += automato.h common.h editautomato.h segmreta.h execautomatos.h
SOURCES += automato.cpp editautomato.cpp main.cpp segmreta.cpp execautomatos.cpp
